Feature/add query parameters
jemberai/data-intake-rag-service pull request #22
Opened 2024-09-23 03:37 UTC by ashokpant

2024-09-24 11:45 UTC, springframeworkguru commented on pom.xml
> +    <!--    <dependencyManagement>-->
Remove this, not needed

2024-09-24 11:45 UTC, springframeworkguru commented on pom.xml
> +        <dependency>
Remove netty, we're not using netty

2024-09-24 11:49 UTC, springframeworkguru commented on src/main/java/org/jemberai/dataintake/service/QueryServiceImpl.java
Properties of Query Request need to be updated, OA3 specification needs to be updated

2024-09-24 11:52 UTC, springframeworkguru commented on src/main/java/org/jemberai/dataintake/service/QueryServiceImpl.java
> +                        .id(chunk.getId().toString())
Add embedding id to query response document, update OA3 specification

2024-09-24 11:58 UTC, springframeworkguru commented on src/main/java/org/jemberai/dataintake/service/QueryServiceImpl.java
> +                        .id(chunk.getId().toString())
Also populate metadata, add parent document id

2024-09-24 11:58 UTC, springframeworkguru requested changes
Please see comments and resolve

2024-10-01 06:56 UTC, ashokpant commented
OA3 specification PR - https://github.com/jemberai/jember-oa3/pull/15

2024-10-08 17:40 UTC, springframeworkguru approved these changes

2024-10-16 03:55 UTC, merged